### PR TITLE
in progress

### PR DESCRIPTION
**Pull request by josephswpark**
Screen Shot 2022-10-19 at 10 13 16 AM

### CODE REVIEW

**Comment by josephswpark** [comment]
Sorry! put the screenshot in the wrong place!

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Joseph! Please only create a pull request when you have completed the assignment and it is ready for review

**Comment by josephswpark** [comment]
Screen Shot 2022-10-19 at 9 33 54 PM

**Review by codingcodymiller — APPROVED** [review]
Nice work!

**Pull request merged**
